import ThemeProvider from "./ThemeProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeSwitcher } from "./components";
import { switchThemeDuration } from "./constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ROMO app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50 dark:bg-[#0d1117] ${switchThemeDuration}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSwitcher/>
            <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
